spring:
  datasource:
    # url: jdbc:postgresql://localhost:50005/room_scheduling_db?currentSchema=auth,resources,booking
    url: jdbc:postgresql://postgres-db:5432/room_scheduling_db?currentSchema=auth,resources,booking
    username: "root"
    password: "password"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"