services:
  postgres-db:
    container_name: room_scheduling_db
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./db/entry.sql:/docker-entrypoint-initdb.d/entry.sql
    ports:
      - "50005:5432"
    expose:
      - "50005"
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=eureka-server
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=password
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - postgres
    depends_on:
      - postgres-db

  config-server:
    container_name: config-server
    image: config-server
    build:
      context: .
      dockerfile: config-server/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "9090:9090"
    networks:
      - postgres
    depends_on:
      - postgres-db
      - eureka-server

  gateway-server:
    container_name: gateway-server
    image: gateway-server
    build:
      context: .
      dockerfile: gateway-server/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - postgres-db
      - eureka-server
      - config-server

  authentication:
    container_name: authentication
    image: authentication
    build:
      context: .
      dockerfile: authentication/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9090
    ports:
      - "9099:9099"
    depends_on:
      - postgres-db
      - eureka-server
      - config-server

  user:
    container_name: user
    image: user
    build:
      context: .
      dockerfile: user/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9090
    ports:
      - "9092:9092"
    depends_on:
      - postgres-db
      - eureka-server
      - config-server
      - authentication
    networks:
      - postgres

  room:
    container_name: room
    image: room
    build:
      context: .
      dockerfile: room/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9090
    ports:
      - "9093:9093"
    depends_on:
      - postgres-db
      - eureka-server
      - config-server
      - authentication
    networks:
      - postgres

  schedule:
    container_name: schedule
    image: schedule
    build:
      context: .
      dockerfile: schedule/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9090
    ports:
      - "9094:9094"
    depends_on:
      - postgres-db
      - eureka-server
      - config-server
      - authentication
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db:
