server:
  port: 9094
  error:
    include-message: always

spring:
  application:
    name: schedule
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:9090"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://config-server:9090"

eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://admin:password@eureka-server:8761/eureka
    register-with-eureka: false
    fetch-registry: false
